-- MySQL Script generated by MySQL Workbench
-- mié 17 sep 2014 13:27:27 CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cambio_precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cambio_precio` (
  `fecha` VARCHAR(45) NULL,
  `codigo_producto` INT NOT NULL,
  `costo_anterior` DECIMAL(2) NOT NULL,
  `costo_actual` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`codigo_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `codigo_producto` INT NULL,
  `existencia` DECIMAL(2) NULL,
  `categoria` INT NULL,
  `precio_venta` DECIMAL(2) NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compras` (
  `fecha` DATE NULL,
  `monto` DECIMAL(2) NULL DEFAULT 0,
  `codigo_producto` INT NOT NULL,
  `cantidad_unidades` INT NULL DEFAULT 0,
  PRIMARY KEY (`codigo_producto`),
  CONSTRAINT `inven-compras`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`inventario` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancelaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cancelaciones` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `clave_empleado` INT NULL,
  `numero_mesa` INT NULL,
  PRIMARY KEY (`folio`),
  INDEX `sec` (`clave_empleado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `clave_empleado` INT NOT NULL,
  `clave_establecimiento` INT NULL,
  `nombre_empleado` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `privilegios` INT NULL DEFAULT 1,
  PRIMARY KEY (`clave_empleado`),
  INDEX `sec` (`clave_establecimiento` ASC),
  CONSTRAINT `can-emp`
    FOREIGN KEY (`clave_empleado`)
    REFERENCES `mydb`.`cancelaciones` (`clave_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`establecimiento` (
  `clave_establecimiento` INT NOT NULL,
  `nombre_establecimiento` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `numero_mesas` INT NULL,
  PRIMARY KEY (`clave_establecimiento`),
  CONSTRAINT `emp-establ`
    FOREIGN KEY (`clave_establecimiento`)
    REFERENCES `mydb`.`empleado` (`clave_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informacion_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`informacion_producto` (
  `codigo_producto` INT NOT NULL,
  `precio_producto` DECIMAL(2) NULL,
  `unidades_paquete` INT NULL,
  `codigo_proveedor` INT NULL,
  PRIMARY KEY (`codigo_producto`),
  INDEX `secundaria` (`codigo_proveedor` ASC),
  CONSTRAINT `referencia1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`compras` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `referencia 3`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`cambio_precio` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `nombre_proveedor` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `codigo_proveedor` INT NOT NULL,
  PRIMARY KEY (`codigo_proveedor`),
  CONSTRAINT `llave_proveedor`
    FOREIGN KEY (`codigo_proveedor`)
    REFERENCES `mydb`.`informacion_producto` (`codigo_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas_dia` (
  `fecha` DATE NOT NULL,
  `cantidad_total` DECIMAL(2) NULL,
  `numero_mesas` INT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas_mesa` (
  `fecha` DATE NULL,
  `numero_mesa` INT NOT NULL,
  PRIMARY KEY (`numero_mesa`),
  INDEX `sec` (`fecha` ASC),
  CONSTRAINT `mesas-ventas`
    FOREIGN KEY (`fecha`)
    REFERENCES `mydb`.`ventas_dia` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
